ip/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("pages.urls")),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.home,name="home"),
    path('search/',views.search,name="search"),



]

pages/models.py
from django.db import models

# Create your models here.

pages/forms.py
from django import forms

class Form(forms.Form):
    ip=forms.CharField(max_length=20)

pages/views.py
from django.shortcuts import render
import requests
import json
from .forms import Form

# Create your views here.

def home(request):
    
    try:
        obj=requests.get("http://ipinfo.io")
        g=True
    except Exception as e:
        g=False
        status="no"
        obj={}

    # obj='{"bla":2,"status_code":200}'
    if(g and obj.status_code == 200 ):
        obj=json.loads(obj.text)
        status="yes"

    else:
        status="no"

    return render(request,'home.html',{"obj":obj,"status":status})


def search(request):

    if (request.method=="POST"):

        form=Form(request.POST)
        print(form)

        if(form.is_valid):
            ip=form.cleaned_data['ip']

            try:
                obj=requests.get("http://ipinfo.io/"+ip)
                g=True
            except Exception as e:
                g=False
                status="no"
                obj={}

            if(g and obj.status_code == 200):
                obj=json.loads(obj.text)
                status="yes"
            else:
                status="no"
  

            return render(request,'home.html',{"obj":obj,"status":status})


    else:
        form=Form()

    return render(request,'search.html',{"form":form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>ip info</title>
    <!-- Bootstrap core CSS -->
    <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/css/blog-post.css" rel="stylesheet">


<style type="text/css"> 
  /*a.nav-link:hover {
    color: white !important;
}*/

body {
    background-color: #e6e6e6;
}

</style>


  </head>


  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">IP Info</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <hr>
            {% block nurl %}


              
            {% endblock nurl %}
          </ul>
        </div>
      </div>
    </nav>


  <!-- Page Content -->
  <div class="container">

    <div class="row">


{% block body %}
  
{% endblock body %}



    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->





<br>
<br>
    <!-- Footer -->
   <!--  <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; IP Info 2019</p>
      </div> -->
      <!-- /.container
    </footer> -->
    <!-- Bootstrap core JavaScript -->
    <script src="/assets/vendor/jquery/jquery.min.js"></script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block nurl %}
          <li class="nav-item ">
            <a class="btn btn-success btn-sm" href=" {% url 'search' %}">Search</a>
          </li>      
{% endblock nurl %}          
    

{% block body %}




      <div class="col-lg-8">
 
        <div class="card my-4" >
          <h5 class="card-header" >Details:</h5>
          <div class="card-body">
  
              <div class="form-group">
{% if status != "yes" %}
  <p class="font-weight-bold">Try again later!!!</p>

{% else %}


               {% for key,val in obj.items  %}

{% if val != '' %}
  <p><span class="text-uppercase font-weight-bold">{{key}}</span> : <span class="text-capitalize font-weight-normal" >{{val}}</span> </p>
  
{% endif %}




                 
               {% endfor %}


{% endif %}






              </div>
             

          </div>
        </div>

       </div>


{% endblock body %}
      


 

templates/search.html
{% extends "base.html" %}
{% block nurl %}
      <li class="nav-item">
            <a class="btn btn-success btn-sm" href=" {% url 'home' %}">Home</a>
          </li>       
{% endblock nurl %}

{% block body %}

<div class="col-lg-8">

    <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">

         <!--      <form method="POST">
                {% csrf_token %}
{{form.ip}}
<br>
  <span class="input-group-btn"> 
                <button class="btn btn-primary" type="Submit">Go!</button>
              </span>

              </form> -->

              <form method="POST">
                {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">IP address</label>
  <!--   <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email"> -->
    {{form.ip}}
  </div>


  <button type="submit" class="btn btn-primary btn-sm">Submit</button>
</form>


   <script type="text/javascript">     

window.onload=function(){

var a=$("#id_ip")[0];
a.className="form-control";
a.placeholder="Enter ip address...";

};


   </script>           
              <!-- <input type="text" class="form-control" placeholder="Search for..."> -->
             
            </div>
          </div>
        </div>
</div>
{% endblock body %}
        